
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Nestor\Documents\Client Diseño Listo\build\assets\frame1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1440x1024")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 1024,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    574.0,
    174.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    294.0,
    304.0,
    image=image_image_2
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    466.5,
    353.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#E4EBF3",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=277.0,
    y=321.0,
    width=379.0,
    height=63.0
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    311.0,
    403.0,
    image=image_image_3
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    466.5,
    452.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#E4EBF3",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=277.0,
    y=420.0,
    width=379.0,
    height=63.0
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    816.0,
    43.0,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    801.0,
    757.0,
    image=image_image_5
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=749.0,
    y=420.0,
    width=232.0,
    height=75.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=981.0,
    y=423.0,
    width=232.0,
    height=75.0
)

canvas.create_rectangle(
    0.0,
    0.0,
    182.0,
    1024.0,
    fill="#175F88",
    outline="")

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    981.0,
    353.0,
    image=image_image_6
)

canvas.create_text(
    703.0,
    312.0,
    anchor="nw",
    text="Estado:",
    fill="#A6A6A6",
    font=("DMSans Medium", 55 * -1)
)

canvas.create_text(
    905.0,
    312.0,
    anchor="nw",
    text="Desvinculado",
    fill="#5F8EC6",
    font=("DMSans Medium", 55 * -1)
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    91.0,
    41.0,
    image=image_image_7
)
window.resizable(False, False)
window.mainloop()
