
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets\FrameMonitoreo")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1440x1024")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 1024,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    182.0,
    1024.0,
    fill="#175F88",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    816.0,
    44.0,
    image=image_image_1
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=6.0,
    y=173.0,
    width=165.0,
    height=89.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=0.0,
    y=89.0,
    width=182.0,
    height=80.0
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    91.0,
    41.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    815.0,
    119.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    815.0,
    283.0,
    image=image_image_4
)

canvas.create_rectangle(
    601.0,
    419.0,
    1030.0,
    968.0,
    fill="#F9F9F9",
    outline="")

canvas.create_text(
    644.0,
    514.0,
    anchor="nw",
    text="Versión del ISO",
    fill="#909090",
    font=("DMSans Medium", 30 * -1)
)

canvas.create_text(
    644.0,
    578.0,
    anchor="nw",
    text="Sistema Operativo",
    fill="#909090",
    font=("DMSans Medium", 30 * -1)
)

canvas.create_text(
    644.0,
    642.0,
    anchor="nw",
    text="CPU",
    fill="#909090",
    font=("DMSans Medium", 30 * -1)
)

canvas.create_text(
    644.0,
    706.0,
    anchor="nw",
    text="Memoria",
    fill="#909090",
    font=("DMSans Medium", 30 * -1)
)

canvas.create_text(
    644.0,
    770.0,
    anchor="nw",
    text="Disco",
    fill="#909090",
    font=("DMSans Medium", 30 * -1)
)

canvas.create_text(
    733.0,
    447.0,
    anchor="nw",
    text="Sin vincular",
    fill="#909090",
    font=("DMSans Medium", 30 * -1)
)
window.resizable(False, False)
window.mainloop()
